### PR TITLE
Fix PSR-4 Autoloading

### PR DESCRIPTION
**Pull request by jaydenn7**
One test needed to be renamed to match the class name

### CODE REVIEW

**Comment by thedotedge** [comment]
Hi, any ETA for merging this?

**Comment by maciejtarnowski** [comment]
Merged, thanks @jaydenn7

The change was only in the test class name, so it's not exactly worth a new tag, but I'm ready to be proven wrong. @thedotedge - do you need a new tag in the project?

**Comment by thedotedge** [comment]
Thanks @maciejtarnowski 👍 Yeah, we do, otherwise we can't really pull a new version in composer.

**Comment by maciejtarnowski** [comment]
This is strange. Just checked version `1.1.0` on Composer 2.0.11 and it doesn't report any PSR-4 related problems.

Anyway, the new tag is version `1.1.1`, I hope it helps. Let me know if it doesn't.

**Pull request merged**
